# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python API Run

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests

            
    - name: Run oag-flightinfo-api
      run: |
        python APIs/oag-flightinfo-api/oagflightinfo.py
      env:
        OAG_SUBSCRIPTION_KEY: ${{ secrets.OAG_SUBSCRIPTION_KEY }}  # Inject the secret as an environment variable   
      
        

